### ISSUE TITLE
bitpanda CSV import

### ISSUE THREAD

**Issue by incognico** [cointracer/cointracer-desktop#1]
bitpanda.com csv import fehlt. Wenn erwünscht kann ich kann eine Beispiel-CSV bereitstellen (via email).

**Comment by YetAnotherCoinGeek** [comment]
Du kannst mir gerne mal eine CSV schicken. Hilfreich wäre es, wenn alle möglichen Transaktionen darin vorkommen würden: Ein- und Auszahlungen, Käufe, Verkäufe usw. E-Mail-Adresse info(at)cointracer.de

**Comment by YetAnotherCoinGeek** [comment]
So lange, wie ich keine Bitpanda-Files habe, kann ich den Import nicht bauen. User perling1 hat aber dankenswerterweise für die Zwischenzeit einen Converter geschrieben, der Bitpanda-Files in CT-Files konvertiert. Ist hier zu finden: [https://github.com/perling1/convertkraken2cointracer](https://github.com/perling1/convertkraken2cointracer)

**Comment by YetAnotherCoinGeek** [comment]
Seit einem Jahr keine Updates zum Thema Bitpanda-Import. Ich schließe das Thema hiermit.
