### ISSUE TITLE
Generischer CSV Import: Fee ist auch Zugang

### ISSUE THREAD

**Issue by CheckQ** [cointracer/cointracer-desktop#11]
Hi, ich hätte hier auch noch was.
Wenn das hier ein Duplicate von dem anderen offenen Issue #8 ist, dann bitte einfach als duplicate markieren und schließen.

### Schritte

- Ich verwende CoinTracer 0.9.7
- Zuerst setze ich bei CoinTracer die gesamte Datenbank zurück.
- Ich verwende den generischen CSV Import.
- ich importiere folgende Zeile:

```
DateTime;Reference;Info;SourcePlatform;SourceCurrency;SourceAmount;TargetPlatform;TargetCurrency;TargetAmount;FeeCurrency;FeeAmount
2020-01-01 01:02:03;Ref001;Info001;Kraken;BTC;1;Kraken;EUR;50000;EUR;70
```

### Ergebnis
![FeeProblemA](https://user-images.githubusercontent.com/11950436/148064230-ae688489-e681-4b74-84b6-16a518032005.png)

Würden wir aber nicht eher die gelben Zahlen erwarten?

**Comment by CheckQ** [comment]
Ich muss gestehen, dass ich immer wieder an meinen Issue Reports zweifel, nachdem ich sie geschrieben habe.

Du schreibst ja "Wenn man Gebühren angibt, müssen Quell-Betrag und Ziel-Betrag als Nettobetrag, d.h. Gebühr abgezogen, ausgewiesen werden!"

Hätte ich die Gebühren jetzt vorher irgendwo abziehen müssen?

Nur mal zum Weiterdenken. Im ersten Beitrag habe ich einen Bitcoin verkauft und war mit den Zahlen in CoinTracer nicht zufrieden. Wenn ich jetzt aber einfach Source und Target umdrehe (also einen Bitcoin kaufe), dann sieht die Import-Zeile folgendermaßen aus:

```
DateTime;Reference;Info;SourcePlatform;SourceCurrency;SourceAmount;TargetPlatform;TargetCurrency;TargetAmount;FeeCurrency;FeeAmount
2020-01-01 01:02:03;Ref001;Info001;Kraken;EUR;50000;Kraken;BTC;1;EUR;70
```

In CoinTracer kommt dann folgendes raus:

![FeeProblemB](https://user-images.githubusercontent.com/11950436/148071673-3caaa94d-c88d-43ff-b1d7-6153296110d0.png)

Und das passt meiner Meinung nach perfekt, obwohl ich die Gebühren ja auch nirgendwo noch extra abgezogen habe.

**Comment by YetAnotherCoinGeek** [comment]
> Du schreibst ja "Wenn man Gebühren angibt, müssen Quell-Betrag und Ziel-Betrag als Nettobetrag, d.h. Gebühr abgezogen, ausgewiesen werden!"
> 
> Hätte ich die Gebühren jetzt vorher irgendwo abziehen müssen?

Ja, du hättest in deinem Beispiel die 70 EUR von den 50.000 abziehen müssen. Ich hätte das jetzt auch anders implementieren können, damit hätte ich allerdings das Einleseverhalten geändert.

Deine erste Zeile hätte also so aussehen müssen:
`DateTime;Reference;Info;SourcePlatform;SourceCurrency;SourceAmount;TargetPlatform;TargetCurrency;TargetAmount;FeeCurrency;FeeAmount
2020-01-01 01:02:03;Ref001;Info001;Kraken;BTC;1;Kraken;EUR;49930;EUR;70`

In deinem zweiten Beispiel verhält sich der CT nach dem gleichen Muster: die 70 EUR werden als Gebühr auf den angegebenen Betrag von 50.000 aufgeschlagen.

Wenn das Thema damit geklärt ist, würde ich es dann schließen.
