### ISSUE TITLE
Generischer CSV Import: Keine Fehlermeldung bei schlechtem Input

### ISSUE THREAD

**Issue by CheckQ** [cointracer/cointracer-desktop#12]
Noch eine Kleinigkeit.

Ich bin wieder beim generischen CSV Import.
Ich habe mehr oder weniger ausversehen folgende Zeile importiert:

```
DateTime;Reference;Info;SourcePlatform;SourceCurrency;SourceAmount;TargetPlatform;TargetCurrency;TargetAmount;FeeCurrency;FeeAmount
2020-01-01 01:02:03;Ref001;Info001;PlatformA;BTC;1;PlatformB;EUR;50000;EUR;70
```

Bei CoinTracer kommt folgendes raus:

![FeeProblemExtern](https://user-images.githubusercontent.com/11950436/148085561-a78e6756-88d3-4ee1-9f61-29b4e9d11cbb.png)

Ich war etwas verwundert, dass die Fee bei der TargetPlatform berechnet wird.
Bisher war meine Annahme, dass Fee immer zur SourcePlatform geht, wenn man nicht explizit was anderes angibt.

Naja, mir ist dann aber aufgefallen, dass die ganze Zeile vermutlich kein erlaubter Input ist.

Es ist ja eine Überweisung von PlatformA nach PlatformB.
Und gleichzeitig ist es auch noch ein Trade von BTC nach EUR.

Vermutlich darf eine Zeile nur entweder Überweisung oder Trade sein?

Meine einzige Anmerkung hier wäre, dass man vielleicht eine Fehlermeldung ausgeben könnte, wenn eine Zeile kein valider Input ist.
Issue ist super low prio. Und du kannst ihn auch sehr gerne mit "wontfix" einfach schließen...

**Comment by YetAnotherCoinGeek** [comment]
> Ich war etwas verwundert, dass die Fee bei der TargetPlatform berechnet wird.
> Bisher war meine Annahme, dass Fee immer zur SourcePlatform geht, wenn man nicht explizit was anderes angibt.

Wenn für die Gebühren keine Plattform angegeben wird (was ja mittels "FeePlatform" möglich ist), dann greift folgende Logik:

1. Wenn nur eine der beiden Plattformen angegeben ist (SourcePlatform oder TargetPlatform), dann gilt (natürlich) diese.
2. Wenn sowohl Target- als auch SourcePlatform spezifiziert ist, dann nimmt der CT diejenige mit der höchsten ID.

Wenn ich so darüber nachdenke, ist Regel 2 irgendwie beliebig gewählt. Wahrscheinlich macht es in der Tat mehr Sinn, hier die SourcePlatform zu unterstellen. Ich baue das bei Gelegenheit mal so um, aber nicht mit hoher Prio. Das Problem lässt sich ja umgehen, indem man einfach eine Spalte "FeePlatform" nutzt.

**Comment by YetAnotherCoinGeek** [comment]
Das Problem ist mit [Version 0.9.7.2](/cointracer/cointracer-desktop/releases/tag/v0.9.7.2) gelöst: die Plattform zu der eine Gebühr gehört, wird jetzt intelligenter ermittelt (zunächst Prüfung auf Währung, bei Ambivalenz wird die Quellplattform angenommen). Außerdem gibt es eine Fehlermeldung, wenn Transfers und Käufe/Verkäufe in einer Datenzeile zusammengefasst wurden.
