### ISSUE TITLE
Binance Import funktioniert (wieder / immer noch) nicht für mich

### ISSUE THREAD

**Issue by tobias-p** [cointracer/cointracer-desktop#13]
Hallo, ich habe probleme beim Import der Zip-Files... meine Order-History wird gar nicht eingelesen, bei der Trade-History schmeißt dein Programm Fehlermeldungen und bricht dann ab...

Ich würde mir auch die Mühe machen und alles per Hand eintragen in CoinTracer - allerdings funktioniert für mich die Logik in dem Programm nicht...

Füge ich einen neuen Trade hinzu (ganz simpel zB Geldeinlage an Binance, 15 Euro bezahlt, 14,71 Euro sind abzgl Gebühren angekommen) und gebe das so ein

![01 Input](https://user-images.githubusercontent.com/10401577/150025030-5aa318d6-209b-48cd-8493-c66cdaa661c7.JPG)

Leider passt das Ergebnis (also was rein kam in Binance) absolut nicht, siehe folgendes Bild

![02 Ergebnis in Cointracer](https://user-images.githubusercontent.com/10401577/150025031-699de39c-e222-4fc9-9c3d-3b2fe460fc26.JPG)

Vielleicht kannst du eine Hilfe erstellen, die einem erklärt, wie man 
1. die Werte manuell eingeben kann / muss,
2. weitere Coins / Währungen eingetragen werden können (ich habe zB aufgrund eines zum damaligen Zeitpunktes günstigen Kurses knapp 20 EUR in Russischen Rubel),
3. wie man Airdrops / Zinsen aus Staking eintragen / buchen würde.

Gerne bin ich auch behilflich mit meiner - recht großen - Export-Datei (Wallet->Overview->Transaction History->Generate all statements - bei mir über 35.000 Zeilen für 2021 - viele davon durch Staking und Liquidity Farming).

_Originally posted by @tobias-p in https://github.com/cointracer/cointracer-desktop/issues/4#issuecomment-1015875105_

**Comment by tobias-p** [comment]
Antwort hatte ich jetzt in dem anderen Thread gepostet, dafür hier nochmal der Link
[Link zu meiner Antwort](https://github.com/cointracer/cointracer-desktop/issues/4#issuecomment-1024967305)

**Comment by YetAnotherCoinGeek** [comment]
Lass uns dann bitte in diesem Thread hier bleiben, issue 14 habe ich geschlossen. Ich kann, wenn ich deine Beispiel-Zeilen einlese, keinen Fehler feststellen, bei mir läuft der Import durch. Allerdings sind bei deinen Zeilen die Zeilenumbrüche „zerschossen“. Achte bei dir doch mal darauf, vielleicht ist bei dir was durcheinander geraten. (Kann passieren, wenn man eine Textdatei mit Linux-Zeilenumbrüchen unter Windows Notepad öffnet und dann wieder speichert.) Ansonsten bräuchte ich die genaue Fehlermeldung.

**Comment by tobias-p** [comment]
Hier die Fehlermeldung - muss aber auch direkt sagen, dass ich bisher nicht weiter mit deinem Programm gearbeitet hatte, da gerade etwas anderes Vorrang hatte. Evtl. hattest du jetzt auch schon ne neue Version, die ich noch nicht installiert habe.

Hier auf jeden Fall die Meldung: 

![03 Fehler](https://user-images.githubusercontent.com/10401577/152643251-2649cb44-68a7-40c7-a181-32b48fbb3059.JPG)

und gleich hinterher mal die komplette Datei, so wie ich die aus Binance bekommen habe..

[part-00000-cc6ae31a-69ef-4263-99fa-3905ce8af0dd-c000.csv](https://github.com/cointracer/cointracer-desktop/files/8008064/part-00000-cc6ae31a-69ef-4263-99fa-3905ce8af0dd-c000.csv)
.

**Comment by YetAnotherCoinGeek** [comment]
Ah, danke für die Infos. Fehler gefunden. Wird im nächsten Release behoben.

**Comment by YetAnotherCoinGeek** [comment]
Das Problem ist in [Version 0.9.7.4](/cointracer/cointracer-desktop/releases/tag/v0.9.7.4) behoben. Der Fehler trat nicht spezifisch beim Binance-Import auf, sondern immer dann, wenn zu viele neue Konten automatisch angelegt wurden. Ist jetzt aber gefixt.
