### ISSUE TITLE
Kraken Import funktioniert nicht

### ISSUE THREAD

**Issue by gu3nter** [cointracer/cointracer-desktop#14]
Hallo,

erstmal vielen Dank für das tolle Programm.
Heute wollte ich alles für meine Steuererklärung vorbereiten, da ist mir aufgefallen, dass wohl der Kraken Import nicht mehr funktioniert.

Könntest du dir das bitte anschauen? 
Falls benötigt, kann ich dir auch gerne meine Datei zu Verfügung stellen, wo der Fehler auftritt.

Gruß

René

**Comment by YetAnotherCoinGeek** [comment]
Hallo gu3nter, ich habe gerade sowohl ledgers als auch trades frisch von Kraken exportiert und problemlos importieren können und kann daher keinen Fehler feststellen. Wenn du mir mehr Informationen zukommen lassen könntest, kann ich genauer forschen.

**Comment by gu3nter** [comment]
Habe eine Mail an info@cointracer.de mit dem kraken ledgers export gesendet, wusste nicht wie ich hier über github ne PN versenden kann.

Hoffe die Mail war korrekt :)

**Comment by YetAnotherCoinGeek** [comment]
Hm, die Mailadresse info@cointracer.de ist korrekt. Allerdings habe ich keine E-Mail bekommen?! Wie groß ist die Datei denn? (Alles über 5 MB lehnt mein Mailrelay ab, glaube ich.) Ggf. müsstest du die Datei noch zippen, damit das bei mir ankommt.

**Comment by gu3nter** [comment]
Hmm die Größe ist nur ca 200kb.

Habe es jetzt nochmal als zip gesendet, hoffe es kommt jetzt an.

Gruß

René

**Comment by YetAnotherCoinGeek** [comment]
Mit dem Release [0.9.7.4](/cointracer/cointracer-desktop/releases/tag/v0.9.7.4) sollte das Problem behoben sein. In deiner Beispiel-Datei gab es viele Trades, deren Betrag so gering war, dass die Gegenbuchung gefehlt hat (weil Fiat-Wert kleiner als 1 Cent). So etwas moniert der CT beim Import grundsätzlich. Die neue Version bricht jetzt in solchen Fällen nicht mehr ab, sondern lässt den User entscheiden, ob der Trade trotzdem importiert werden soll. Außerdem kann man jetzt eine Toleranzgrenze in den Einstellungen (Import-Einstellungen) definieren, unterhalb derer betreffende Trades einfach ohne Meldung importiert werden.

**Comment by gu3nter** [comment]
Cool danke für alles

**Comment by gu3nter** [comment]
Hi, sorry, dass ich mich jetzt erst melde, war lange Zeit verhindert mir alles im Detail anzuschauen.

Könntest du bitte den von mir gesendeten CSV Export nochmal prüfen?
Mir wird hier bei ALGO -36,.... angezeigt, habe aber in Wirklichkeit 0,0

ALGO wurde von mir das erste Mal im bereits gesendeten Jahr getradet, somit, sollte meiner Meinung nach auch 0,0 angezeigt werden.

Danke für deine Mühe
