### ISSUE TITLE
Kraken API Import 

### ISSUE THREAD

**Issue by Blacksheep70** [cointracer/cointracer-desktop#17]
I am getting with 0.9.7.6 following error with the Kraken API import

![grafik](https://user-images.githubusercontent.com/8124924/176102561-fcbf3d56-6c2e-4432-81e6-546943da49ab.png)

Happens also with older versions now, e.g. 0.9.6.2

**Comment by Blacksheep70** [comment]
Add: *.csv import works fine for me

**Comment by YetAnotherCoinGeek** [comment]
Indeed, there was a slight change in the way Kraken handles api requests, so I had to change some parameters. This is fixed in the latest [release 0.9.7.7](https://github.com/cointracer/cointracer-desktop/releases/tag/v0.9.7.7)
