### ISSUE TITLE
Can not fetch latest USD currency data

### ISSUE THREAD

**Issue by ghost** [cointracer/cointracer-desktop#2]
Updating the USD currency data stops at 27.11.2019 and throws error message:

"The remote certificate is invalid according to the validation procedure."

**Comment by YetAnotherCoinGeek** [comment]
I have just released a new version today. Do you still have this problem?

**Comment by ghost** [comment]
Thanks for getting back and for the updates! (Just installed 0.9.5.1).

The issue occurred once that day. After that, it worked always fine. So we can close the issue here.

BTW, I encountered different issues with the older version:

https://coinforum.de/topic/2411-trading-gewinnermittlung-für-die-steuer-softwaregestützt/page/19/?tab=comments#comment-528214

 I'm going to retest them and open new issues on GitHub if necessary.
