### ISSUE TITLE
Haltefrist Berechnung

### ISSUE THREAD

**Issue by N-Schaef** [cointracer/cointracer-desktop#3]
Hallo,
erstmal Danke für das tolle Tool!

Leider habe ich ein Problem, bei der Gewinnberechnung mit folgenden Settings scheint mir die Haltefrist nicht beachtet zu werden:
![grafik](https://user-images.githubusercontent.com/7281529/109139959-63344a80-775c-11eb-9e43-cff34163e94d.png)

Denn all meine Verkäufe werden als nicht Steuerfrei angesehen, obwohl die Haltefrist über einem Jahr ist.
![grafik](https://user-images.githubusercontent.com/7281529/109140736-359bd100-775d-11eb-9850-dcee2027d90b.png)

Oder verstehe ich etwas falsch?

Version 0.9.5.0 (public beta)

**Comment by YetAnotherCoinGeek** [comment]
Oh, das ist tatsächlich ein Bug. Der Wert Steuerfrei wird nicht korrekt in die Tabelle geschrieben. Ich versuche das morgen zu beheben und eine neue Version live zu stellen. Danke für den Hinweis!

**Comment by YetAnotherCoinGeek** [comment]
Habe gerade die Version 0.9.5.1 hochgeladen. Damit müsste das Problem behoben sein.
