### ISSUE TITLE
request binance import 

### ISSUE THREAD

**Issue by hAislt** [cointracer/cointracer-desktop#4]
Hi,
erstmal danke dafür, dass das Tool zur Verfügung steht.
Wäre es möglich Binance csv importe zu implementieren?
Eine Datei könnte ich zur Verfügung stellen.
Merci und Grüße

**Comment by YetAnotherCoinGeek** [comment]
Klar, wenn du mir eine CSV schicken würdest, schaue ich mir das gerne an. In der CSV sollten möglichst alle Arten von Transaktionen enthalten sein (also Ein- und Auszahlung, Kauf, Verkauf). Gerne per PM oder einfach per Mail an info(at)cointracer.de

**Comment by saimkaan** [comment]
Hey,
wird hier schon dran gearbeitet?

**Comment by saimkaan** [comment]
Date(UTC),Pair,Side,Price,Executed,Amount,Fee
2021-05-09 22:47:36,VETUSDT,BUY,0.2291700000,43.7000000000VET,10.01472900USDT,0.0000114300BNB
2021-05-09 22:30:55,VETUSDT,BUY,0.2313200000,43.7000000000VET,10.10868400USDT,0.0000114200BNB
2021-05-09 22:22:42,LTCUSDT,SELL,370.6000000000,0.0281300000LTC,10.42497800USDT,0.0000118000BNB
2021-05-09 20:48:13,LTCUSDT,BUY,359.1700000000,0.0281300000LTC,10.10345210USDT,0.0000114300BNB
2021-05-09 20:39:01,XMRUSDT,SELL,473.7400000000,0.0220000000XMR,10.42228000USDT,0.0000117900BNB
2021-05-09 19:43:23,ADAUSDT,BUY,1.7526000000,11.4200000000ADA,20.01469200USDT,0.0000230600BNB
2021-05-09 19:20:01,ADAUSDT,BUY,1.7705000000,5.6500000000ADA,10.00332500USDT,0.0000114300BNB

**Comment by saimkaan** [comment]
Habe leider keine Daten für Ein- und Auszahlung

**Comment by saimkaan** [comment]
![image](https://user-images.githubusercontent.com/15209875/117739627-01359e00-b1ff-11eb-8d1d-ceac107a9db1.png)

**Comment by perling1** [comment]
Habe einen Binance 2 cointracer Converter als Powershell Script geschrieben. Liegt frei auf github.
https://github.com/perling1/convertkraken2cointracer/blob/main/convertbinance2cointracer.ps1
Damit entsteht eine cointracer formatierte datei für importe.

**Comment by hAislt** [comment]
Danke! ich schau mal rein, habe von @YetAnotherCoinGeek leider keine Rückmeldung mehr erhalten nachdem ich die Exports gesendet habe. Habe es mit der Binance API selbst versucht aber da gibt es keine saubere trade Bilanz.

**Comment by YetAnotherCoinGeek** [comment]
So, ich habe jetzt eine neue Version 0.9.7 live gestellt, mit der auch Dateien von Binance.com verarbeitet werden können. Und zwar sowohl trade history files (wie sie oben beschrieben sind) als auch convert history und deposit oder withdrawal files. Dieses Ticket hier schließe ich dann einstweilen.

**Comment by Cj5VdMzj0B** [comment]
Ich bin mir jetzt wirklich nicht sicher...aber ich glaube die Datenstruktur und Dateiart von oben hat sich inzwischen geändert. Ich habe das mal mit dem ersten getestet, der Trade History (Binance->Orders->Spot Orders->Trade History->Export->Beyond 6 month - custom->Zeitspanne von 2021 eingestellt->Export). Bei diesem Export habe ich eine *.zip Datei erhalten in welcher eine *.csv Datei komprimiert gewesen ist. Der Import hat mit dieser Datei 1:1 schonmal nicht geklappt. Beim vergleichen der obigen Struktur und der Erklärung beim Import sind mir folgende Unterschiede aufgefallen:
1. Es handelt sich um eine *.csv Datei, keine *.xlsx
2. Der Header hat sich geändert: Date(UTC),Pair,Side,Price,Executed,Amount,Fee
3. Bei den 3 Spalten Executed,Amount,Fee ist der Wert jetzt keine reine Zahl mehr, sondern die Zahl + Währung z.B. 0.0379080000BTC

Bsp. meiner exportierten Datei:
Date(UTC),Pair,Side,Price,Executed,Amount,Fee
2021-01-11 15:33:05,BTCEUR,BUY,"26,500.0000000000",0.0379080000BTC,"1,004.56200000EUR",0.0000000000BTC
2021-01-06 20:55:01,BTCUSDT,SELL,"36,000.0000000000",0.0018610000BTC,66.99600000USDT,0.0669960000USDT

Bin ich irgendwo falsch abgebogen oder habe etwas übersehen? Muss noch eine Konvertierung durchgeführt werden?

**Comment by YetAnotherCoinGeek** [comment]
Ich habe das gerade mal nachvollzogen. Und in der Tat: bei größeren Zeitspannen erzeugt Binance nicht direkt XLSX-Dateien zum Download, sondern gezippte CSV-Dateien. Das Format müsste ich noch einbauen. Kommt in die nächste Version (wann ich das fertig habe, kann ich noch nicht sagen).

**Comment by Cj5VdMzj0B** [comment]
Interessant....aber nicht wirklich logisch, warum implementiert man (Binance) den gleichen Export 2mal und dann auch noch anders :D. Hatte ich tatsächlich auch noch nicht gemerkt, hab immer im 3 Monatsrythmus alles heruntergeladen (maximale Zeitspanne). Weist du zufällig bis zu welchem max. Zeitraum man *.xlsx Dateien von Binance bekommt?

**Comment by YetAnotherCoinGeek** [comment]
So, ich habe gerade ein neues Release (0.9.7.1) veröffentlicht. Jetzt werden auch Trades als Zip-Datei verarbeitet. :-)

**Comment by Cj5VdMzj0B** [comment]
Ich Danke recht herzlich :).

**Comment by tobias-p** [comment]
Hallo, ich habe probleme beim Import der Zip-Files... meine Order-History wird gar nicht eingelesen, bei der Trade-History schmeißt dein Programm Fehlermeldungen und bricht dann ab...

Ich würde mir auch die Mühe machen und alles per Hand eintragen in CoinTracer - allerdings funktioniert für mich die Logik in dem Programm nicht...

Füge ich einen neuen Trade hinzu (ganz simpel zB Geldeinlage an Binance, 15 Euro bezahlt, 14,71 Euro sind abzgl Gebühren angekommen) und gebe das so ein

![01 Input](https://user-images.githubusercontent.com/10401577/150025030-5aa318d6-209b-48cd-8493-c66cdaa661c7.JPG)

Leider passt das Ergebnis (also was rein kam in Binance) absolut nicht, siehe folgendes Bild

![02 Ergebnis in Cointracer](https://user-images.githubusercontent.com/10401577/150025031-699de39c-e222-4fc9-9c3d-3b2fe460fc26.JPG)

Vielleicht kannst du eine Hilfe erstellen, die einem erklärt, wie man 
1. die Werte manuell eingeben kann / muss,
2. weitere Coins / Währungen eingetragen werden können (ich habe zB aufgrund eines zum damaligen Zeitpunktes günstigen Kurses knapp 20 EUR in Russischen Rubel),
3. wie man Airdrops / Zinsen aus Staking eintragen / buchen würde.

Gerne bin ich auch behilflich mit meiner - recht großen - Export-Datei (Wallet->Overview->Transaction History->Generate all statements - bei mir über 35.000 Zeilen für 2021).

**Comment by YetAnotherCoinGeek** [comment]
> Hallo, ich habe probleme beim Import der Zip-Files... meine Order-History wird gar nicht eingelesen, bei der Trade-History schmeißt dein Programm Fehlermeldungen und bricht dann ab...

**Order**-Histories kann der CT nicht verarbeiten, nur **Trade**-History-Files. Wenn es bei deinen Trade-Dateien zu Fehlermeldungen kommt, dann ist eine Ferndiagnose ohne Beispiel schwierig. Könntest du mir mal exemplarisch ein paar Zeilen aus der History schicken (inkl. Kopfzeile, in der die Spaltennamen stehen)? Dann könnte ich mir das näher ansehen.

**Comment by YetAnotherCoinGeek** [comment]
> Vielleicht kannst du eine Hilfe erstellen, die einem erklärt, wie man
> 
>     1. die Werte manuell eingeben kann / muss,
> 
>     2. weitere Coins / Währungen eingetragen werden können (ich habe zB aufgrund eines zum damaligen Zeitpunktes günstigen Kurses knapp 20 EUR in Russischen Rubel),
> 
>     3. wie man Airdrops / Zinsen aus Staking eintragen / buchen würde.

ad 1: Der Screenshot oben sieht schon nicht schlecht aus. Dass in der Übersicht beim Bestand als "Abgang" -15 EUR angezeigt werden, liegt daran, dass auch die Auszahlung von 15 EUR von der Bank als Abgang gezählt wird. Wenn du über der Liste auf "Plattformen anzeigen" klickst, kann man das besser erkennen.

ad 2: Weitere Coins kannst du bei den Tabellen unter "Konten" eingeben. Rechte Maustaste "Konten bearbeiten", neuer Datensatz (das Plus oben links). Bei Rubel sehe ich allerdings das Problem, dass man nur neue Coins anlegen kann und keine neuen Fiat-Währungen. (Das hat damit zu tun, dass der CT alle Fiat-Trades intern mit einem EUR-Wert versieht. Für die Umrechnung von USD zu EUR habe ich das Abrufen von Wechselkursen eingebaut. Für Rubel gibt's so einen Mechanismus nicht.) Wenn du also Rubel anlegst, wäre das für den CT ein Crypto-Asset und würde als solches behandelt (was steuerlich bestimmt Unsinn wäre).

ad 3: Es gibt ja offenbar noch keine verbindlichen steuerlichen Regeln zu Airdrops oder erhaltenen Staking-Rewards. Eine Möglichkeit wäre, das als Transfer von "Extern" auf die Zielplattform zu erfassen. Bei einem eventuellen Weiterverkauf der erhaltenen Coins/Rewards wird dann allerdings immer ein Erwerbspreis von 0 EUR angenommen, d.h. dass der gesamte Verkaufserlös (abzgl. Gebühren) als Gewinn betrachtet wird.

**Comment by tobias-p** [comment]
Hi, erstmal sorry, dass es so lange keine Antwort von mir gab, ich hatte meinen Post noch einmal als extra Issue aufgemacht und immer nur da geschaut... *sorry*

Nun zu deinen Antworten:

> **Order**-Histories kann der CT nicht verarbeiten, nur **Trade**-History-Files. Wenn es bei deinen Trade-Dateien zu Fehlermeldungen kommt, dann ist eine Ferndiagnose ohne Beispiel schwierig. Könntest du mir mal exemplarisch ein paar Zeilen aus der History schicken (inkl. Kopfzeile, in der die Spaltennamen stehen)? Dann könnte ich mir das näher ansehen.

Hier die ersten 8 Zeilen aus der Trade History (direkt aus der csv rauskopiert)... Hoffentlich hilft dir das so weiter

`
Date(UTC),Pair,Side,Price,Executed,Amount,Fee
2021-12-16 08:35:18,BTCEUR,BUY,"43,188.0800000000",0.0002800000BTC,12.09266240EUR,0.0000192000BNB
2021-08-07 16:27:08,FRONTBTC,BUY,0.0000254100,9.8000000000FRONT,0.00024902BTC,0.0000230300BNB
2021-07-24 13:24:26,CHRBTC,BUY,0.0000102300,80.0000000000CHR,0.00081840BTC,0.0000683900BNB
2021-07-22 07:25:36,BTCRUB,SELL,"2,401,925.0000000000",0.0005450000BTC,"1,309.04912500RUB",1.3090491300RUB
2021-06-29 12:34:37,USDTRUB,SELL,72.5720000000,3.4000000000USDT,246.74480000RUB,0.0000082000BNB
2021-06-27 10:22:06,ADXBTC,SELL,0.0000105600,15.0000000000ADX,0.00015840BTC,0.0000001600BTC
2021-06-15 12:23:49,VETUSDT,BUY,0.1131100000,88.4000000000VET,9.99892400USDT,0.0000202700BNB
`

> ad 1: Der Screenshot oben sieht schon nicht schlecht aus. Dass in der Übersicht beim Bestand als "Abgang" -15 EUR angezeigt werden, liegt daran, dass auch die Auszahlung von 15 EUR von der Bank als Abgang gezählt wird. Wenn du über der Liste auf "Plattformen anzeigen" klickst, kann man das besser erkennen.

Das hab ich ja mal gar nicht gesehen 🙈. Nach der Einblendung ist die Anzeige deutlich sinnvoller (eventuell als Standard setzen?)...

> ad 2: Weitere Coins kannst du bei den Tabellen unter "Konten" eingeben. Rechte Maustaste "Konten bearbeiten", neuer Datensatz (das Plus oben links). Bei Rubel sehe ich allerdings das Problem, dass man nur neue Coins anlegen kann und keine neuen Fiat-Währungen. (Das hat damit zu tun, dass der CT alle Fiat-Trades intern mit einem EUR-Wert versieht. Für die Umrechnung von USD zu EUR habe ich das Abrufen von Wechselkursen eingebaut. Für Rubel gibt's so einen Mechanismus nicht.) Wenn du also Rubel anlegst, wäre das für den CT ein Crypto-Asset und würde als solches behandelt (was steuerlich bestimmt Unsinn wäre).

Steuerlich zwar wahrscheinlich nicht perfekt, aber immer noch besser, als gar nicht drin... Vielleicht kannst du den Wechselkurs aber auch einbauen - worüber rufst du den im Quellcode ab?

> ad 3: Es gibt ja offenbar noch keine verbindlichen steuerlichen Regeln zu Airdrops oder erhaltenen Staking-Rewards. Eine Möglichkeit wäre, das als Transfer von "Extern" auf die Zielplattform zu erfassen. Bei einem eventuellen Weiterverkauf der erhaltenen Coins/Rewards wird dann allerdings immer ein Erwerbspreis von 0 EUR angenommen, d.h. dass der gesamte Verkaufserlös (abzgl. Gebühren) als Gewinn betrachtet wird.

Da hast du recht, steuerlich ist da leider noch gar nichts festgelegt. Da ich im steuerlichen Bereich allerdings tätig bin, kann ich innerhalb der nächsten 2 Wochen mal rausbekommen, wie das mein Chef bzw. ein paar Kollegen von mir sehen bzw. wie wir das steuerlich gehandhabt haben bei Mandanten. Hier weiß ich allerdings nicht, ob Airdrops / Staking bei den Mandanten mit bei waren... Ansonsten wäre ich auch gewillt bei der Finanzverwaltung mal anzurufen und zu fragen, wie solche "Gewinne" aufzeichnungstechnisch behandelt werden müssten.

Einen Import für die komplette Transaction-History planst du aktuell zufällig nicht, oder? Ich hätte da eine entsprechend große Datei, an der du dich austoben könntest 😅.
