### ISSUE TITLE
Kraken Import Error

### ISSUE THREAD

**Issue by Marbel** [cointracer/cointracer-desktop#5]
Hi,

Ich benutze dein Programm bereits seit 2 Jahren und bin sehr zufrieden :) 
Ich hab seit kurzem ein Problem mit dem Import von meinen Trades(Ledgers) bei Kraken. 
![image](https://user-images.githubusercontent.com/5067628/115762255-90d7f180-a3a3-11eb-83ea-5a2726501731.png)

Die Fehlermeldung öffnet sich immer wieder beim bestätigen oder schließen, nur die "Nr." des Trades wird hochgezählt. z.b.
![image](https://user-images.githubusercontent.com/5067628/115764227-98989580-a3a5-11eb-819c-a1a31a264ead.png)
Ich muss CoinTracer dann über den Task Manager beenden.

Die damit zusammenhängenden Vorgänge:
```
"txid","refid","time","type","subtype","aclass","asset","amount","fee","balance"
"LUORUM-K64YQ-QI2F2A","TVY7HB-D2IGA-ITRM2E","2021-04-11 03:22:22","trade","","currency","XXMR",-0.0000050900,0.0000000000,0.0000000100
"LDK6GY-I5I5O-IGR5DI","TVY7HB-D2IGA-ITRM2E","2021-04-11 03:22:22","trade","","currency","ZEUR",0.0013,0.0000,797.7421
```

Der Debug log zu dem Fehler:
[https://pastebin.com/YkJJCTgd](https://pastebin.com/YkJJCTgd)

Erwartetes Verhalten ist: Das ich wieder Kraken Imports über die Api oder CSV machen kann.

Vielen Dank für die gute Arbeit :)

**Comment by YetAnotherCoinGeek** [comment]
Danke dir für die detaillierte Meldung. Ich habe mir das Problem in der Log-Datei angesehen und glaube, es mit der nächsten CT-Version beheben zu können. (Kommt am WE)

**Comment by YetAnotherCoinGeek** [comment]
Neue Version ist raus, das Problem sollte behoben sein.
