### ISSUE TITLE
Fiat to Fiat

### ISSUE THREAD

**Issue by CheckQ** [cointracer/cointracer-desktop#6]
Ich habe eine Kraken ledgers.csv importiert, die Fiat/Fiat Transaktionen enthält. Ich glaube, damit kommt CoinTracer nicht klar.

Beispiel:
Bei Kraken habe ich 500 EUR und 0 USD.

Nun möchte ich 300 USD kaufen und dafür 250 EUR bezahlen.
Das Kraken Trading Pair dafür lautet ZEURZUSD.

Bei Kraken wird das nun leider eine SELL ORDER (obwohl ich vorher ja gar nichts gekauft hatte).
Ich VERKAUFE 250 EUR und bekomme dafür dann 300 USD.

CoinTracer denkt nun, dass hier etwas zu versteuern ist, weil ja ein Verkauf stattgefunden hat.
CoinTracer kann aber keinen zugehörigen Kauf finden (n/a in Spalte Kaufvorgang) und will 100% versteuern.

Falls du dir das mal anschauen möchtest, helfe ich gerne.
Wenn dir das Thema zu blöd ist, hab ich dafür auch Verständnis.
Vielen Dank jedenfalls für das coole Tool.

**Comment by CheckQ** [comment]
Ok, ich habe noch etwas weiter geforscht.
In der ledgers.csv steht ja gar nicht drin, ob etwas eine Buy-Order oder eine Sell-Order ist.
Das muss CoinTracer also selber irgendwie entscheiden.

Ich glaube, er schaut bei jedem Trade nach, ob der Nicht-Fiat-Teil (z.B. Bitcoin) von einem Trade mehr oder weniger wird.
Wird er mehr, dann ist es eine Buy-Order.
Wird er weniger,dann ist es eine Sell-Order.

Wenn nun aber beide Seiten von einem Trade Fiat Währungen sind, dann importiert CoinTracer es in meinem Fall gerade falsch herum was dann im weiteren Verlauf zu falschen Berechnung führt.

---

Dazu passt auch ein **WORKAROUND** für diesen Issue:
Wenn ich in der ledger.csv ein Suchen & Ersetzen mache und dabei all "ZUSD" ersetze durch irgendwas zufälliges anderes (z.B. "USDU"), dann funktioniert alles perfekt. CoinTracer nimmt dann an, dass das irgendein seltsamer Coin ist und legt in der Tabelle 'Konten' auch automatisch zwei neue Zeilen "SDU" und "Gebühr SDU" an.
Ich muss mir dann halt selber merken, dass "SDU" eigenltich US-Dollar ist.

**Comment by YetAnotherCoinGeek** [comment]
Den Case Fiat gegen Fiat habe ich in der Tat beim Kraken-Import bisher nicht vorgesehen (das Feature gab's auch nicht von Anfang an). Ich würde es kurzfristig so bauen, dass Transfers Fiat gegen Fiat immer als Kauf interpretiert werden. Dann wird auch im Steuerbericht kein Gewinn ausgewiesen. Das würde dann passen für Ankäufe von z.B. USD gegen EUR. 

Die Gegenrichtung ist aber - genau genommen - problematischer: wenn man USD gegen EUR tauscht, dann müsste das nach meinem Verständnis steuerlich als Verkauf betrachtet werden, bei dem ein Gewinn/Verlust erzielt wird. Der CT müsste für diese Fälle die USD wie Cryptocoins behandeln und tracken, zu welchem Kurs USD angeschafft wurden, um das sauber berechnen zu können. Bei der Gewinnberechnung werden EUR oder USD aktuell allerdings nicht als zu trackende Assets eingestuft. Der Wert von USD richtet sich aktuell immer nach dem jeweiligen EUR/USD-Tageskurs, und nicht nach dem Anschaffungspreis. Das umzubauen wäre schon ein größerer Aufwand.

Also: Schritt eins = Fiat gegen Fiat immer als Kauf importieren. Und dann sehen wir weiter...

**Comment by YetAnotherCoinGeek** [comment]
So, die neue CT-Version ist veröffentlich. Jetzt werden Transaktionen Fiat vs. Fiat auf Kraken immer als Käufe betrachtet.
