### ISSUE TITLE
Kraken import USDT (Tether)

### ISSUE THREAD

**Issue by CheckQ** [cointracer/cointracer-desktop#7]
Ich importiere eine Kraken ledgers.csv, die USDT Trades enthält.
Im Tab "Tabellen" -> Tab "Konten" gibt es bereits die Zeilen "USDT" und "feeUSDT".
Dort werden die Tether Trades aber nicht einsortiert.
Es werden neue Zeilen angelegt mit den Namen "SDT" und "feeSDT" und dort wird Tether dann einsortiert.

Vielleicht lässt du bei den Kraken Imports immer den ersten Buchstaben weg?

Bei vielen anderen Währungskürzeln passt das ja auch:
XXBT = XBT = Bitcoin
XETH = ETH = Ethereum
ZEUR = EUR = Euro

Bei Tether passt das Schema leider nicht :/
USDT ist nicht "SDT" sondern "USDT"

Kein schlimmer Issue. Ich wollte ihn aber hier trotzdem mal erwähnen.

**Comment by YetAnotherCoinGeek** [comment]
Danke für den Hinweis. Ich habe die Kraken-Importlogik jetzt so geändert, dass der erste Buchstabe nur dann ignoriert wird, wenn es ein "X" oder ein "Z" ist. Das müsste dann ja eigentlich passen. Am Wochenende kommt die neue Version.

**Comment by YetAnotherCoinGeek** [comment]
Neue Version ist raus, ich schließe das Thema.
