### ISSUE TITLE
Berechnungsfehler Report Berichtsvorschau Kauf & Verkaufgebühren fehlen

### ISSUE THREAD

**Issue by Geistesblitz8** [cointracer/cointracer-desktop#8]
Version 0.9.6.0
Import: CSV manuell
Li-Fo

In der aktuellen Version werden die kompletten Gebühren Kauf- und Verkauf außer acht gelassen. Dieses tritt sowohl auf, wie hier am Beispiel beim verschieben der Coins von Börse A zu Börse B, wie auch beim ganz normalen Kauf und späteren Verkaufsprozess. Die Gebühren sind jedoch importiert worden. 

Ich denke das hier nur die Feldzuordnung fehlerhaft ist.

Hier mal ein Beispielszenario:
![falsche_berechnung_beispiel](https://user-images.githubusercontent.com/89070947/129711703-2c9e79fb-1b8d-449e-bb52-d82aa97c0738.PNG)

**Comment by YetAnotherCoinGeek** [comment]
Okay, das Problem ist verstanden. Bei der Berechnung des Gewinns sollte der Kaufkurs die Gebühren beinhalten, weil ansonsten der Gewinn zu hoch ausfällt. Das schaue ich mir an!

**Comment by YetAnotherCoinGeek** [comment]
Wird in der nächsten Version korrigiert.

**Comment by YetAnotherCoinGeek** [comment]
Problem mit [Version 0.9.7.2](/cointracer/cointracer-desktop/releases/tag/v0.9.7.2) gelöst. Kauf- und Transfergebühren werden jetzt korrekt berücksichtigt.
