### ISSUE TITLE
Generischer CSV Import

### ISSUE THREAD

**Issue by CheckQ** [cointracer/cointracer-desktop#9]
### Mein Vorhaben:

- Ich verwende CoinTracer 0.9.6.2
- Zuerst setze ich bei CoinTracer die gesamte Datenbank zurück.
- Ich verwende den generischen CSV Import (nicht den Kraken Import).
- Ich transferiere 100 ADA (Bruttobetrag) von Kraken auf meine Hardware-Wallet.
  Dabei berechnet mir Kraken eine Gebühr von 4 ADA.
  (alles fiktive Werte)

### Meine Erwartung, was am Ende in ConTracer rauskommen sollte:

![Expectation](https://user-images.githubusercontent.com/11950436/144941175-c0db81bb-7eea-4061-bc62-e2b1f1b53b69.png)

Liege ich mit dieser Erwartung vielleicht schon falsch?

Das mit den -100 ADA sieht jetzt vielleicht etwas seltsam aus. Aber ich versuche mein Problem der Einfachheit halber mit nur einer Zeile in der CSV-Datei zu beschreiben.

## Versuch A
Lese ich beim [CoinTracer-Importformat](https://www.cointracer.de/?q=node/6) den Text "Wenn man Gebühren angibt, müssen Quell-Betrag und Ziel-Betrag als Nettobetrag, d.h. Gebühr abgezogen, ausgewiesen werden!", dann würde ich erwarten:
```
DateTime;Reference;Info;SourcePlatform;SourceCurrency;SourceAmount;TargetPlatform;TargetCurrency;TargetAmount;FeePlatform;FeeCurrency;FeeAmount
2020-01-01 01:02:03;Ref001;Info001;Kraken;ADA;96,0;WalletOwn;ADA;96,0;Kraken;ADA;4,0
```
Da kommt aber nicht das richtige raus.

## Versuch B

Lese ich beim [CoinTracer-Importformat](https://www.cointracer.de/?q=node/6) die Zahlen in der Beispiel-Spalte (SourceAmount=30,45, TargetAmount=30,4, FeeAmount=0,05), dann könnte ich auch auf folgende Idee kommen:
```
DateTime;Reference;Info;SourcePlatform;SourceCurrency;SourceAmount;TargetPlatform;TargetCurrency;TargetAmount;FeePlatform;FeeCurrency;FeeAmount
2020-01-01 01:02:03;Ref001;Info001;Kraken;ADA;100,0;WalletOwn;ADA;96,0;Kraken;ADA;4,0
```
Da kommt aber auch nicht das richtige raus.

## Versuch C

Tatsächlich komme ich nur mit folgender Zeile zum gewünschten Ergebnis:
```
DateTime;Reference;Info;SourcePlatform;SourceCurrency;SourceAmount;TargetPlatform;TargetCurrency;TargetAmount;FeePlatform;FeeCurrency;FeeAmount
2020-01-01 01:02:03;Ref001;Info001;Kraken;ADA;96,0;WalletOwn;ADA;92,0;Kraken;ADA;4,0
```
Meine Vermutung ist, dass das so eher nicht sein soll.

**Comment by YetAnotherCoinGeek** [comment]
Danke für den Hinweis. In der Tat gab es das Problem, dass beim Import im CT-Format Gebühren nicht in allen Fällen berücksichtigt wurden. Das ist mit dem jüngsten Commit korrigiert ([ef200fb](https://github.com/cointracer/cointracer-desktop/commit/ef200fb6fc93ee3dd9577d34288cdc0751a040ec))
